plugins {
    id 'java'
    id 'java-library'
    id 'maven-publish'
    id 'sml6' version '0.2.0-a20260820.2'
    id 'eclipse'
}

group = 'de.geolykt'
// Hint: The version is defined in the gradle.properties file!

base {
    archivesName = 's2dmenues'
}

java.targetCompatibility = compileJava.targetCompatibility = java.sourceCompatibility = compileJava.sourceCompatibility = '1.8'

repositories {
    maven {
        name = 'stianloader-maven'
        url = 'https://stianloader.org/maven'
    }

    maven {
        name = 'jitpack'
        url = 'https://jitpack.io'
    }

    mavenCentral()
    mavenLocal()
}

configurations {
    sllLauncher

    compileOnly.extendsFrom(sllLauncher)

    dependencyMods

    compileOnlyApi.extendsFrom(dependencyMods)
}


task fetchGame(type: org.stianloader.sml6.tasks.FetchGameTask) {
    steamApplicationName = 'Galimulator'
    steamApplicationId = 808100
    steamJarPath = 'jar/galimulator-desktop.jar'
    outputs.upToDateWhen { false }

    symlinkDirectories = [ "data" ]
}

task deobfGame(type: org.stianloader.sml6.tasks.DeobfuscateGameTask) {
    inputJar = fetchGame.outputJar
}

task stripGame(type: org.stianloader.sml6.tasks.StripDependenciesTask) {
    inputJar = deobfGame.outputJar

    stripGalimulatorDefaults502 {
        configurations['compileOnlyApi'].extendsFrom(it)
    }
}

task stripObfGame(type: org.stianloader.sml6.tasks.StripDependenciesTask) { // Required for properly generating member realms in the obfuscated namespace
    inputJar = fetchGame.outputJar
    filteringEntryNames = stripGame.filteringEntryNames
    strippingDependencies = stripGame.strippingDependencies
}

task remapGame(type: org.stianloader.sml6.tasks.RemapJarTask) {
    inputJar = stripGame.outputJar
    libraryJars = stripGame.strippingDependencies

    archiveBaseName = "galimulator"
    archiveClassifier = "remapped"
    archiveVersion = deobfGame.autodeobfVersion
    destinationDirectory = layout.buildDirectory.dir('sml6/remapGame')

    addMappingsFile {
        containerFormat = XZ
        mappingFormat = TINY_2
        downloadMavenResource("de.geolykt:bstarmap:${bStarmapVersion}@tinyv2.xz", 'stianloader-nightlies', 'https://stianloader.org/maven/')
    }
}

task genSources(type: org.stianloader.sml6.tasks.GenerateSourcesTask) {
    inputJar = remapGame.archiveFile
    libraryClasspath = stripGame.strippingDependencies

    outputSourcesJar = outputDirectory.file('galimulator-remapped-5.0.2-sources.jar')
    lineRemappedOutputJar = outputDirectory.file('galimulator-remapped-5.0.2.jar')

    decompileOptions {
        removeSynthetic = false
        verifyAnonymousClasses = true
        includeJavaRuntime = true
    }
}

compileJava {
    dependsOn tasks.named('genSources')
}

task remapJar(type: org.stianloader.sml6.tasks.RemapJarTask) {
    inputJar = jar.archiveFile
    libraryJars = configurations.named('compileClasspath')

    archiveBaseName = jar.archiveBaseName
    archiveClassifier = 'remapped'
    archiveVersion = jar.archiveVersion
    destinationDirectory = base.libsDirectory

    addMappingsFile {
        containerFormat = XZ
        mappingFormat = TINY_2
        downloadMavenResource("de.geolykt:bstarmap:${bStarmapVersion}@tinyv2.xz", 'stianloader-nightlies', 'https://stianloader.org/maven/')
        srcNamespaceId = 0
        dstNamespaceId = -1
    }

    addMappingsFile {
        containerFormat = PLAIN
        mappingFormat = TINY
        mappingSource = deobfGame.spStarmapMappings
        srcNamespaceId = 0
        dstNamespaceId = -1
    }

    addMappingsFile {
        containerFormat = PLAIN
        mappingFormat = TINY
        mappingSource = deobfGame.slIntermediaryMappings
        srcNamespaceId = 0
        dstNamespaceId = -1 // This inverts source and destination namespaces (default source namespace id is -1)
    }
}

task deployMods(type: org.stianloader.sml6.tasks.DeployModsTask) {
    dependsOn stripObfGame // Required for the artifact transform to not blow up
    dependsOn deobfGame

    mods = configurations.named('dependencyMods').map {
        it.incoming.artifactView {
            attributes {
                attribute(ArtifactTypeDefinition.ARTIFACT_TYPE_ATTRIBUTE, 'predeploy-mod')
            }
        }.files
    }
}

task runMods(type: org.stianloader.sml6.tasks.SLLJavaExecTask) {
    dependsOn tasks.named('deployMods')

    classpath configurations['sllLauncher']

    bootGameDependencies = stripGame.strippingDependencies
    bootGameJar = genSources.lineRemappedOutputJar
    gameMainClass = 'com.example.Main'

    usingModSourceSet(tasks.named('compileJava'), java.sourceSets.named('main'))

    systemProperties.put('classloader.dump', 'true')
    systemProperties.put('org.stianloader.sll.log.level', 'DEBUG')
    systemProperties.put('org.stianloader.micromixin.debug', true)

    javaLauncher = javaToolchains.launcherFor {
        languageVersion = JavaLanguageVersion.of(17)
        vendor = JvmVendorSpec.JETBRAINS
    }
}

eclipse {
    synchronizationTasks genSources
}

build {
    dependsOn tasks.named('remapJar')
}

task genEclipseRuns(type: org.stianloader.sml6.tasks.GenerateEclipseRunTask) {
    dependsOn tasks.named('deployMods')
    from tasks.named('runMods')
}

org.stianloader.sml6.WellOfDespair.registerDependency(project, configurations.named('compileOnly')) {
    configurationName = 'galimulatorElements'
    capabilityName = 'org.stianloader:galimulator:5.0.2'
    artifactJar = genSources.lineRemappedOutputJar
    sourcesJar = genSources.outputSourcesJar

    dependency {
        attributes {
            attribute(org.stianloader.sml6.transforms.attributes.RASTransform.RAS_TRANSFORM_ATTRIBUTE, objects.named(org.stianloader.sml6.transforms.attributes.RASTransform, 'transform-buildtime'))
        }
    }
}

dependencies {
    attributesSchema {
        attribute(org.stianloader.sml6.transforms.attributes.RASTransform.RAS_TRANSFORM_ATTRIBUTE) {
            disambiguationRules.add(org.stianloader.sml6.transforms.attributes.RASDisambiguationRule)
            compatibilityRules.add(org.stianloader.sml6.transforms.attributes.RASCompatibilityRule)
        }
    }

    artifactTypes {
        named(ArtifactTypeDefinition.JAR_TYPE) {
            attributes.attribute(org.stianloader.sml6.transforms.attributes.RASTransform.RAS_TRANSFORM_ATTRIBUTE, objects.named(org.stianloader.sml6.transforms.attributes.RASTransform, 'transform'))
        }
    }

    registerTransform(org.stianloader.sml6.transforms.RemapArtifactTransform) {
        from.attribute(ArtifactTypeDefinition.ARTIFACT_TYPE_ATTRIBUTE, 'jar')
        to.attribute(ArtifactTypeDefinition.ARTIFACT_TYPE_ATTRIBUTE, 'predeploy-mod')

        parameters {
            libraryJars.from(stripObfGame.outputJar)

            addMappingsFile {
                containerFormat = PLAIN
                mappingFormat = TINY
                mappingSource = deobfGame.slIntermediaryMappings
            }

            addMappingsFile {
                containerFormat = PLAIN
                mappingFormat = TINY
                mappingSource = deobfGame.spStarmapMappings
            }

            addMappingsFile {
                containerFormat = XZ
                mappingFormat = TINY_2
                downloadMavenResource("de.geolykt:bstarmap:${bStarmapVersion}@tinyv2.xz", 'stianloader-nightlies', 'https://stianloader.org/maven/')
            }
        }
    }

    registerTransform(org.stianloader.sml6.transforms.ApplyRASArtifactTransform) {
        from.attribute(org.stianloader.sml6.transforms.attributes.RASTransform.RAS_TRANSFORM_ATTRIBUTE, objects.named(org.stianloader.sml6.transforms.attributes.RASTransform, 'transform'))
        to.attribute(org.stianloader.sml6.transforms.attributes.RASTransform.RAS_TRANSFORM_ATTRIBUTE, objects.named(org.stianloader.sml6.transforms.attributes.RASTransform, 'transform-buildtime'))

        parameters {
            scope = BUILDTIME
            inputFile = project.file('src/main/resources/s2dmenues.ras')
            outputArtifactType = ''
        }
    }

    sllLauncher 'org.stianloader:launcher-micromixin:4.0.0-a20260611'

    dependencyMods('de.geolykt:starloader-api:2.0.0-a20260214:remapped') {
        transitive = false
    }

    compileOnly 'org.stianloader:micromixin-annotations:0.6.2-a20240731'
    compileOnly 'de.geolykt.starloader:starplane-annotations:1.0.0'
    compileOnlyApi 'org.jetbrains:annotations:26.1.0'

    compileOnly("com.github.raeleus.TenPatch:tenpatch:$tenpatchVersion") {
        exclude group: 'com.badlogicgames.gdx', module: 'gdx'
    }

    compileOnly("com.github.tommyettinger:textratypist:$textraTypistVersion") {
        exclude group: 'com.badlogicgames.gdx', module: 'gdx'
    }
}

processResources {
    def version = project.property('version')
    def tenpatchVersion = project.property('tenpatchVersion')
    def textraTypistVersion = project.property('textraTypistVersion')

    inputs.property('version', version)
    inputs.property('tenpatchVersion', tenpatchVersion)
    inputs.property('textraTypistVersion', textraTypistVersion)

    filesMatching('extension.json') {
        expand(
            'version': version,
            'tenpatchVersion': tenpatchVersion,
            'textraTypistVersion': textraTypistVersion
        )
    }
}

publishing {
    publications {
        plugin(MavenPublication) { publication ->
            groupId = project.group
            artifactId = project.base.archivesName.get()

            from components['java']
            artifact remapJar.asArtifact()
        }
    }

    repositories {
        if (System.getProperty('publishRepo') != null) {
            maven {
                url = System.getProperty('publishRepo')
                allowInsecureProtocol = true
            }
        } else {
            mavenLocal()
        }
    }
}

eclipse {
    classpath {
      containers 'org.eclipse.buildship.core.gradleclasspathcontainer'
      file {
            whenMerged {
                def source = entries.find { it.path == 'org.eclipse.buildship.core.gradleclasspathcontainer' }
                source.entryAttributes['annotationpath'] = 'src/eclipse-eea'
            }
        }
    }
}
