plugins {
    id 'java'
    id 'java-library'
    id 'maven-publish'
    id 'sml6' version '0.3.0-a20260828'
    id 'eclipse'
}

group = 'de.geolykt'
// Hint: The version is defined in the gradle.properties file!

base {
    archivesName = 's2dmenues'
}

java.targetCompatibility = compileJava.targetCompatibility = java.sourceCompatibility = compileJava.sourceCompatibility = '25'

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(25)
    }
}

repositories {
    maven {
        name = 'stianloader-maven'
        url = 'https://stianloader.org/maven'
    }

    maven {
        name = 'jitpack'
        url = 'https://jitpack.io'
    }

    mavenCentral()
    mavenLocal()
}

configurations {
    sllLauncher
    lwjgl3Classpath
    runtimeGalimulator

    compileOnly.extendsFrom(sllLauncher)

    dependencyMods

    compileOnlyApi.extendsFrom(dependencyMods)
    compileOnlyApi.extendsFrom(lwjgl3Classpath)
    compileOnly.extendsFrom(runtimeGalimulator)
}

task fetchGame(type: org.stianloader.sml6.tasks.FetchGameTask) {
    steamApplicationName = 'Galimulator'
    steamApplicationId = 808100
    steamJarPath = 'jar/galimulator-desktop.jar'
    outputs.upToDateWhen { false }

    symlinkDirectories = [ 'data' ]
}

task deobfGame(type: org.stianloader.sml6.tasks.DeobfuscateGameTask) {
    inputJar = fetchGame.outputJar
}

task stripGame(type: org.stianloader.sml6.tasks.StripDependenciesTask) {
    inputJar = deobfGame.outputJar
    stripGalimulatorDefaults502()
}

task stripObfGame(type: org.stianloader.sml6.tasks.StripDependenciesTask) { // Required for properly generating member realms in the obfuscated namespace
    inputJar = fetchGame.outputJar
    filteringEntryNames = stripGame.filteringEntryNames
    strippingDependencies = stripGame.strippingDependencies
}

task remapGame(type: org.stianloader.sml6.tasks.RemapJarTask) {
    inputJar = stripGame.outputJar
    libraryJars = stripGame.strippingDependencies

    archiveBaseName = 'galimulator'
    archiveClassifier = 'remapped'
    archiveVersion = deobfGame.autodeobfVersion
    destinationDirectory = layout.buildDirectory.dir('sml6/remapGame')

    addMappingsFile {
        containerFormat = XZ
        mappingFormat = TINY_2
        downloadMavenResource("de.geolykt:bstarmap:${bStarmapVersion}@tinyv2.xz", 'stianloader-nightlies', 'https://stianloader.org/maven/')
    }
}

task genSources(type: org.stianloader.sml6.tasks.GenerateSourcesTask) {
    inputJar = remapGame.archiveFile
    libraryClasspath = stripGame.strippingDependencies

    outputSourcesJar = outputDirectory.file('galimulator-remapped-5.0.2-sources.jar')
    lineRemappedOutputJar = outputDirectory.file('galimulator-remapped-5.0.2.jar')

    decompileOptions {
        removeSynthetic = false
        verifyAnonymousClasses = true
        includeJavaRuntime = true
    }
}

compileJava {
    dependsOn tasks.named('genSources')
}

task remapJar(type: org.stianloader.sml6.tasks.RemapJarTask) {
    inputJar = jar.archiveFile
    libraryJars = configurations.named('compileClasspath')

    archiveBaseName = jar.archiveBaseName
    archiveClassifier = 'remapped'
    archiveVersion = jar.archiveVersion
    destinationDirectory = base.libsDirectory

    addMappingsFile {
        containerFormat = XZ
        mappingFormat = TINY_2
        downloadMavenResource("de.geolykt:bstarmap:${bStarmapVersion}@tinyv2.xz", 'stianloader-nightlies', 'https://stianloader.org/maven/')
        srcNamespaceId = 0
        dstNamespaceId = -1
    }

    addMappingsFile {
        containerFormat = PLAIN
        mappingFormat = TINY
        mappingSource = deobfGame.spStarmapMappings
        srcNamespaceId = 0
        dstNamespaceId = -1
    }

    addMappingsFile {
        containerFormat = PLAIN
        mappingFormat = TINY
        mappingSource = deobfGame.slIntermediaryMappings
        srcNamespaceId = 0
        dstNamespaceId = -1 // This inverts source and destination namespaces (default source namespace id is -1)
    }
}

task deployMods(type: org.stianloader.sml6.tasks.DeployModsTask) {
    dependsOn stripObfGame // Required for the artifact transform to not blow up
    dependsOn deobfGame

    mods = configurations.named('dependencyMods').map {
        it.incoming.artifactView {
            attributes {
                attribute(ArtifactTypeDefinition.ARTIFACT_TYPE_ATTRIBUTE, 'predeploy-mod')
            }
        }.files
    }
}

eclipse {
    synchronizationTasks genSources
}

build {
    dependsOn tasks.named('remapJar')
}

org.stianloader.sml6.WellOfDespair.registerDependency(project, configurations.named('runtimeGalimulator')) {
    configurationName = 'galimulatorElements'
    capabilityName = 'org.stianloader:galimulator:5.0.2'
    artifactJar = genSources.lineRemappedOutputJar
    sourcesJar = genSources.outputSourcesJar

    dependency {
        attributes {
            attribute(org.stianloader.sml6.transforms.attributes.RASTransform.RAS_TRANSFORM_ATTRIBUTE, objects.named(org.stianloader.sml6.transforms.attributes.RASTransform, 'transform-buildtime'))
            attribute(org.stianloader.sml6.transforms.attributes.LWJGLVersion.LWJGL_VERSION_ATTRIBUTE, 3)
        }
    }

    configuration {
        outgoing {
            attributes {
                attribute(org.stianloader.sml6.transforms.attributes.LWJGLVersion.LWJGL_VERSION_ATTRIBUTE, 2)
            }
        }
    }
}

dependencies {
    attributesSchema {
        attribute(org.stianloader.sml6.transforms.attributes.RASTransform.RAS_TRANSFORM_ATTRIBUTE) {
            disambiguationRules.add(org.stianloader.sml6.transforms.attributes.RASDisambiguationRule)
            compatibilityRules.add(org.stianloader.sml6.transforms.attributes.RASCompatibilityRule)
        }
        attribute(org.stianloader.sml6.transforms.attributes.LWJGLVersion.LWJGL_VERSION_ATTRIBUTE)
    }

    artifactTypes {
        named(ArtifactTypeDefinition.JAR_TYPE) {
            attributes.attribute(org.stianloader.sml6.transforms.attributes.RASTransform.RAS_TRANSFORM_ATTRIBUTE, objects.named(org.stianloader.sml6.transforms.attributes.RASTransform, 'transform'))
        }
    }

    registerTransform(org.stianloader.sml6.transforms.RemapArtifactTransform) {
        from.attribute(ArtifactTypeDefinition.ARTIFACT_TYPE_ATTRIBUTE, 'jar')
        to.attribute(ArtifactTypeDefinition.ARTIFACT_TYPE_ATTRIBUTE, 'predeploy-mod')

        parameters {
            libraryJars.from(stripObfGame.outputJar)

            addMappingsFile {
                containerFormat = PLAIN
                mappingFormat = TINY
                mappingSource = deobfGame.slIntermediaryMappings
            }

            addMappingsFile {
                containerFormat = PLAIN
                mappingFormat = TINY
                mappingSource = deobfGame.spStarmapMappings
            }

            addMappingsFile {
                containerFormat = XZ
                mappingFormat = TINY_2
                downloadMavenResource("de.geolykt:bstarmap:${bStarmapVersion}@tinyv2.xz", 'stianloader-nightlies', 'https://stianloader.org/maven/')
            }
        }
    }

    registerTransform(org.stianloader.sml6.transforms.ApplyRASArtifactTransform) {
        from.attribute(org.stianloader.sml6.transforms.attributes.RASTransform.RAS_TRANSFORM_ATTRIBUTE, objects.named(org.stianloader.sml6.transforms.attributes.RASTransform, 'transform'))
        to.attribute(org.stianloader.sml6.transforms.attributes.RASTransform.RAS_TRANSFORM_ATTRIBUTE, objects.named(org.stianloader.sml6.transforms.attributes.RASTransform, 'transform-buildtime'))

        parameters {
            scope = BUILDTIME
            inputFile = project.file('src/main/resources/s2dmenues.ras')
            outputArtifactType = ''
        }
    }

    registerTransform(org.stianloader.sml6.transforms.MigrateLWJGL3ArtifactTransform) {
        from.attribute(org.stianloader.sml6.transforms.attributes.LWJGLVersion.LWJGL_VERSION_ATTRIBUTE, 2)
        to.attribute(org.stianloader.sml6.transforms.attributes.LWJGLVersion.LWJGL_VERSION_ATTRIBUTE, 3)
    }

    sllLauncher 'org.stianloader:launcher-micromixin:4.0.0-a20260611'

    dependencyMods('de.geolykt:starloader-api:2.0.0-a20260824:remapped') {
        transitive = false
    }

    dependencyMods("de.geolykt:star-cell-shading:${starCellShadingVersion}:remapped") {
        transitive = false
    }

    compileOnly 'org.stianloader:micromixin-annotations:0.6.2-a20240731'
    compileOnly 'de.geolykt.starloader:starplane-annotations:1.0.0'
    compileOnlyApi 'org.jetbrains:annotations:26.1.0'

    compileOnly("com.github.raeleus.TenPatch:tenpatch:$tenpatchVersion") {
        exclude group: 'com.badlogicgames.gdx', module: 'gdx'
    }

    compileOnly("com.github.tommyettinger:textratypist:$textraTypistVersion") {
        exclude group: 'com.badlogicgames.gdx', module: 'gdx'
    }

    // Source: https://mvnrepository.com/artifact/com.code-disaster.steamworks4j/steamworks4j-gdx
    lwjgl3Classpath 'com.code-disaster.steamworks4j:steamworks4j-gdx:1.10.0'

    // Source: https://mvnrepository.com/artifact/com.badlogicgames.gdx/gdx-backend-lwjgl3
    lwjgl3Classpath("com.badlogicgames.gdx:gdx-backend-lwjgl3:${libGDXVersion}") {
        exclude group: 'org.lwjgl', module: 'lwjgl'
        exclude group: 'org.lwjgl', module: 'lwjgl-glfw'
        exclude group: 'org.lwjgl', module: 'lwjgl-openal'
        exclude group: 'org.lwjgl', module: 'lwjgl-opengl'
        exclude group: 'org.lwjgl', module: 'lwjgl-jemalloc'
        exclude group: 'org.lwjgl', module: 'lwjgl-stb'
    }

    // Source: https://mvnrepository.com/artifact/com.badlogicgames.gdx/gdx-platform
    lwjgl3Classpath "com.badlogicgames.gdx:gdx-platform:${libGDXVersion}:natives-desktop"
    lwjgl3Classpath 'com.thoughtworks.xstream:xstream:1.4.7'

    for (String classifier : ['', ':natives-linux', ':natives-linux-arm32', ':natives-linux-arm64']) { // windows and mac support has been dropped.
        for (String variant: ['', '-openal', '-opengl', '-glfw', '-jemalloc', '-stb', '-harfbuzz']) {
            lwjgl3Classpath "org.lwjgl:lwjgl${variant}:${lwjglVersion}${classifier}"
        }
    }

    runtimeGalimulator 'org.stianloader:lwjgl3ify:2.0.0-a20260820'
}

task runMods(type: org.stianloader.sml6.tasks.SLLJavaExecTask) {
    dependsOn tasks.named('deployMods')

    classpath configurations.named('sllLauncher')

    bootFiles.from(configurations.named('lwjgl3Classpath'))
    bootFiles.from(configurations.named('runtimeGalimulator'))

    gameMainClass = 'com.example.Main'

    usingModSourceSet(tasks.named('compileJava'), java.sourceSets.named('main'))

    systemProperties.put('classloader.dump', 'true')
    systemProperties.put('org.stianloader.sll.log.level', 'DEBUG')
    systemProperties.put('org.stianloader.micromixin.debug', true)
    systemProperties.put('org.stianloader.lwjgl3ify.killOnReturn', true)
    systemProperties.put('de.geolykt.s2dmenues.preferX11', true)

    javaLauncher = javaToolchains.launcherFor {
        languageVersion = JavaLanguageVersion.of(25)
        //vendor = JvmVendorSpec.JETBRAINS
    }

    renderdocExecutable = 'renderdoc_1.45/bin/renderdoccmd'
}

task genEclipseRuns(type: org.stianloader.sml6.tasks.GenerateEclipseRunTask) {
    dependsOn tasks.named('deployMods')
    from tasks.named('runMods')
    notCompatibleWithConfigurationCache('Upstream SML6 issue.');
}

processResources {
    def version = project.property('version')
    def tenpatchVersion = project.property('tenpatchVersion')
    def textraTypistVersion = project.property('textraTypistVersion')
    def starCellShadingVersion = project.property('starCellShadingVersion')

    inputs.property('version', version)
    inputs.property('tenpatchVersion', tenpatchVersion)
    inputs.property('textraTypistVersion', textraTypistVersion)
    inputs.property('starCellShadingVersion', starCellShadingVersion)

    filesMatching('extension.json') {
        expand(
            'version': version,
            'tenpatchVersion': tenpatchVersion,
            'textraTypistVersion': textraTypistVersion,
            'starCellShadingVersion': starCellShadingVersion
        )
    }
}

publishing {
    publications {
        plugin(MavenPublication) { publication ->
            groupId = project.group
            artifactId = project.base.archivesName.get()

            from components['java']
            artifact remapJar.asArtifact()
        }
    }

    repositories {
        if (System.getProperty('publishRepo') != null) {
            maven {
                url = System.getProperty('publishRepo')
                allowInsecureProtocol = true
            }
        } else {
            mavenLocal()
        }
    }
}

eclipse {
    classpath {
      containers 'org.eclipse.buildship.core.gradleclasspathcontainer'
      file {
            whenMerged {
                def source = entries.find { it.path == 'org.eclipse.buildship.core.gradleclasspathcontainer' }
                source.entryAttributes['annotationpath'] = 'src/eclipse-eea'
            }
        }
    }
}
