org.gradle.configuration-cache=true
org.gradle.parallel=true
org.gradle.caching=true

bStarmapVersion=0.0.1-a20260817.1
tenpatchVersion=5.2.3
# https://mvnrepository.com/artifact/com.github.tommyettinger/textratypist
textraTypistVersion=2.2.12
version=0.4.0
# https://stianloader.org/maven/de/geolykt/star-cell-shading/
starCellShadingVersion=0.5.0-a20260824.1

# Note: When adding new properties here, remember to also add them in the processResources block!
